Rails 6.1
PrecisionNutrition/smart_listing pull request #2
Opened 2021-01-26 14:42 UTC by jherdman

2021-01-29 15:22 UTC, elucid requested changes

2021-01-29 15:22 UTC, elucid commented on lib/smart_listing.rb
> +             end
nope

2021-02-01 17:36 UTC, elucid requested changes
Small suggestion

2021-02-01 17:36 UTC, elucid commented on lib/smart_listing.rb
> +      attr = attr.split('.')[1] if attr.starts_with?(klass_name) && attr.include?('.')
How about

```suggestion
      attr = attr.split('.')[1] if attr.starts_with?("#{klass_name}.")
```

2021-02-01 17:36 UTC, jherdman commented on lib/smart_listing.rb
> +      attr = attr.split('.')[1] if attr.starts_with?(klass_name) && attr.include?('.')
Looks great!

2021-02-01 17:46 UTC, elucid approved these changes

2021-02-01 19:13 UTC, merged